BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Class";
CREATE TABLE "Class" (
	"Id"	INTEGER,
	"Name"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Item";
CREATE TABLE "Item" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"AegisName"	TEXT,
	"Name"	TEXT,
	"ItemTypeId"	INTEGER,
	"ItemSubTypeId"	INTEGER,
	"Buy"	INTEGER,
	"Sell"	INTEGER,
	"Weight"	INTEGER,
	"Custom"	INTEGER DEFAULT 0,
	PRIMARY KEY("Id"),
	FOREIGN KEY("ItemSubTypeId") REFERENCES "ItemSubType"("Id"),
	FOREIGN KEY("ItemTypeId") REFERENCES "ItemType"("Id")
);
DROP TABLE IF EXISTS "ItemSubType";
CREATE TABLE "ItemSubType" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "ItemType";
CREATE TABLE "ItemType" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Job";
CREATE TABLE "Job" (
	"Id"	INTEGER,
	"Name"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Map";
CREATE TABLE "Map" (
	"Id"	INTEGER,
	"MapId"	TEXT NOT NULL,
	"Name"	TEXT,
	"Custom"	INTEGER DEFAULT 0,
	"Implemented"	INTEGER DEFAULT 1,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Mob";
CREATE TABLE "Mob" (
	"Id"	INTEGER,
	"AegisName"	TEXT UNIQUE,
	"Name"	TEXT,
	"Level"	INTEGER DEFAULT 1,
	"Hp"	INTEGER DEFAULT 1,
	"Sp"	INTEGER DEFAULT 1,
	"BaseExp"	INTEGER DEFAULT 0,
	"JobExp"	INTEGER DEFAULT 0,
	"MvpExp"	INTEGER DEFAULT 0,
	"Attack"	INTEGER DEFAULT 0,
	"Attack2"	INTEGER DEFAULT 0,
	"Defense"	INTEGER DEFAULT 0,
	"MagicDefense"	INTEGER DEFAULT 0,
	"Resistance"	INTEGER DEFAULT 0,
	"MagicResistance"	INTEGER DEFAULT 0,
	"Str"	INTEGER DEFAULT 1,
	"Agi"	INTEGER DEFAULT 1,
	"Vit"	INTEGER DEFAULT 1,
	"Int"	INTEGER DEFAULT 1,
	"Dex"	INTEGER DEFAULT 1,
	"Luk"	INTEGER DEFAULT 1,
	"AttackRange"	INTEGER DEFAULT 0,
	"SkillRange"	INTEGER DEFAULT 0,
	"ChaseRange"	INTEGER DEFAULT 0,
	"Size"	INTEGER,
	"Race"	INTEGER,
	"Element"	INTEGER,
	"ElementLevel"	INTEGER DEFAULT 1,
	"WalkSpeed"	INTEGER,
	"AttackDelay"	INTEGER DEFAULT 0,
	"AttackMotion"	INTEGER DEFAULT 0,
	"ClientAttackMotion"	INTEGER,
	"DamageMotion"	INTEGER DEFAULT 0,
	"DamageTaken"	INTEGER DEFAULT 100,
	"GroupId"	INTEGER DEFAULT 0,
	"Title"	INTEGER,
	"Ai"	INTEGER DEFAULT 06,
	"Class"	INTEGER,
	PRIMARY KEY("Id")
);
DROP TABLE IF EXISTS "MobDrop";
CREATE TABLE "MobDrop" (
	"Id"	INTEGER,
	"MobId"	INTEGER,
	"Slot"	INTEGER,
	"ItemId"	INTEGER,
	"Rate"	INTEGER,
	"StealProtected"	INTEGER DEFAULT 0,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("MobId","Slot"),
	FOREIGN KEY("ItemId") REFERENCES "Item"("Id"),
	FOREIGN KEY("MobId") REFERENCES "Mob"("Id")
);
DROP TABLE IF EXISTS "MobElement";
CREATE TABLE "MobElement" (
	"Id"	INTEGER,
	"Name"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "MobJob";
CREATE TABLE "MobJob" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "MobMvpDrop";
CREATE TABLE "MobMvpDrop" (
	"Id"	INTEGER,
	"MobId"	INTEGER,
	"Slot"	INTEGER,
	"ItemId"	INTEGER,
	"Rate"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("MobId","Slot"),
	FOREIGN KEY("ItemId") REFERENCES "Item"("Id"),
	FOREIGN KEY("MobId") REFERENCES "Mob"("Id")
);
DROP TABLE IF EXISTS "MobRace";
CREATE TABLE "MobRace" (
	"Id"	INTEGER,
	"Name"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "MobSize";
CREATE TABLE "MobSize" (
	"Id"	INTEGER,
	"Name"	TEXT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "Npc";
CREATE TABLE "Npc" (
	"Id"	INTEGER,
	"Name"	TEXT,
	"MapId"	INTEGER,
	"X"	INTEGER,
	"Y"	INTEGER,
	"Facing"	INTEGER,
	"Icon"	INTEGER,
	"Custom"	INTEGER DEFAULT 0,
	"Implemented"	INTEGER DEFAULT 1,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("MapId","X","Y"),
	FOREIGN KEY("MapId") REFERENCES "Map"("Id")
);
DROP TABLE IF EXISTS "NpcItem";
CREATE TABLE "NpcItem" (
	"Id"	INTEGER,
	"NpcId"	INTEGER,
	"Slot"	INTEGER,
	"ItemId"	INTEGER,
	"Quantity"	INTEGER DEFAULT 0,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("NpcId","Slot"),
	FOREIGN KEY("ItemId") REFERENCES "Item"("Id"),
	FOREIGN KEY("NpcId") REFERENCES "Npc"("Id")
);
DROP TABLE IF EXISTS "Recipe";
CREATE TABLE "Recipe" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL UNIQUE,
	"RecipeTypeId"	INTEGER NOT NULL,
	"JobId"	INTEGER NOT NULL DEFAULT 0,
	"Repeatable"	INTEGER DEFAULT 0,
	"Custom"	INTEGER DEFAULT 0,
	PRIMARY KEY("Id" AUTOINCREMENT),
	FOREIGN KEY("JobId") REFERENCES "Job"("Id"),
	FOREIGN KEY("RecipeTypeId") REFERENCES "RecipeType"("Id")
);
DROP TABLE IF EXISTS "RecipeItem";
CREATE TABLE "RecipeItem" (
	"Id"	INTEGER,
	"RecipeId"	INTEGER NOT NULL,
	"ItemId"	INTEGER NOT NULL,
	"RecipeItemTypeId"	INTEGER NOT NULL,
	"Quantity"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("Id" AUTOINCREMENT),
	UNIQUE("RecipeId","ItemId","RecipeItemTypeId"),
	FOREIGN KEY("ItemId") REFERENCES "Item"("Id"),
	FOREIGN KEY("RecipeId") REFERENCES "Recipe"("Id"),
	FOREIGN KEY("RecipeItemTypeId") REFERENCES "RecipeItemType"("Id")
);
DROP TABLE IF EXISTS "RecipeItemType";
CREATE TABLE "RecipeItemType" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "RecipeType";
CREATE TABLE "RecipeType" (
	"Id"	INTEGER,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
